"""KPI definitions, and the scenarios that deviate from them.

Every number this project reports comes from one builder. A definition is a set
of clauses with the agreed answer as the default, and a scenario is that
definition with exactly one clause changed. That construction is what makes the
discrepancies attributable: a scenario that moved two clauses at once would
produce a number that differs for two reasons and explain neither.

Two consequences are worth stating plainly, because they are the design.

* The agreed definition is generated by the same code as the defective ones. If
  the correction were written out separately, the audit would be comparing an
  analyst's query against another analyst's query, and a reader would have to take
  on trust which of the two was right. Here the correct answer is the default
  argument, and each scenario is a named departure from it.
* The rows a definition aggregates are generated by the same builder as the value
  it reports. So the audit can state not only that a figure moved but how many
  rows were wrongly included or excluded, and the two statements cannot drift
  apart.

Severity is derived from the relative size of the discrepancy against the agreed
figure, through bands stated in this module. Nothing is labelled by hand.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace

# The bands, in relative terms: how far the reported figure sits from the agreed
# one, as a fraction of the agreed one. Relative rather than absolute, because a
# defect that moves a billion naira by ten million and a defect that moves a
# hundred thousand naira by ten million are not the same accusation.
#
# The medium band is deliberately low. A defect that moves a headline figure by
# two percent is worth a ticket, and a threshold set at ten percent would classify
# a silently dropped status feed as a rounding note.
DISCREPANCY_BANDS = {"high": 0.10, "medium": 0.02}

# The reporting window, as one clause rather than as a start, an end and an
# operator. That is deliberate. A closed upper bound is only meaningfully wrong
# in combination with the date it closes on, so splitting the two would make the
# final day defect change two clauses, and a scenario that changes two clauses
# cannot be attributed to either one.
#
# The agreed window is half open, from the first instant of the period up to but
# not including the first instant of the next. The closed window is the same
# period written with an inclusive upper bound, which is what loses the final day
# once the column carries a time of day.
PERIOD_START = "2025-01-01"
PERIOD_LAST_DAY = "2025-06-30"
PERIOD_END_EXCLUSIVE = "2025-07-01"

WINDOWS = {
    "H1_HALF_OPEN": (PERIOD_START, PERIOD_END_EXCLUSIVE, "half_open"),
    "FEB_TO_JUN": ("2025-02-01", PERIOD_END_EXCLUSIVE, "half_open"),
    "H1_CLOSED": (PERIOD_START, PERIOD_LAST_DAY, "inclusive"),
}

WINDOW_NAMES = tuple(WINDOWS)

STATUSES_NOT_REVENUE = ("CANCELLED", "RETURNED")


def severity_for_relative(relative: float) -> str | None:
    """Map a relative discrepancy onto a severity, or None if there is none.

    A discrepancy of zero is not a finding. Neither is a reported figure that
    beats the agreed one: a scenario whose number is larger or smaller than the
    agreed number for a documented reason is still reported, in whichever
    direction it moved, because a KPI that understates is as much a reporting
    defect as one that overstates. Only a number that agrees raises nothing.
    """
    if relative == 0:
        return None
    if relative >= DISCREPANCY_BANDS["high"]:
        return "high"
    if relative >= DISCREPANCY_BANDS["medium"]:
        return "medium"
    return "low"


# Which measure a definition reports. ``order_lines`` is the count of rows rather
# than orders, and it is here as a measure in its own right because counting rows
# and calling the result orders is a defect with a name, not a typo.
MEASURES = ("net_revenue", "orders", "order_lines")

MEASURE_EXPRESSIONS = {
    "net_revenue": "ROUND(SUM(f.net_amount), 2)",
    "orders": "COUNT(DISTINCT f.order_id)",
    "order_lines": "COUNT(f.line_id)",
}

MEASURE_UNITS = {
    "net_revenue": "currency",
    "orders": "count",
    "order_lines": "count",
}

# How unknown statuses are treated. ``agreed`` books an order whose status feed
# has not arrived, because it is not known to be cancelled. ``exclude_unknown``
# writes the same intent as a ``NOT IN``, which is not the same predicate: a null
# status fails every comparison, so the row disappears.
STATUS_RULES = ("agreed", "exclude_unknown", "only_cancelled")


@dataclass(frozen=True)
class Definition:
    """One KPI definition, as clauses. The defaults are the agreed definition.

    A scenario is built by replacing one field. The dataclass is frozen so that a
    replacement produces a new definition rather than editing the agreed one,
    which is what keeps the agreed definition constant across the whole audit.
    """

    measure: str = "net_revenue"
    dedupe: bool = True
    window: str = "H1_HALF_OPEN"
    status_rule: str = "agreed"
    region_join: str = "left"
    channel_join: str = "left"
    qualify: bool = True

    def __post_init__(self) -> None:
        if self.measure not in MEASURES:
            raise ValueError(
                f"Unknown measure {self.measure!r}. Expected one of {list(MEASURES)}."
            )
        if self.window not in WINDOWS:
            raise ValueError(
                f"Unknown window {self.window!r}. Expected one of {list(WINDOW_NAMES)}."
            )
        if self.status_rule not in STATUS_RULES:
            raise ValueError(
                f"Unknown status rule {self.status_rule!r}. Expected one of "
                f"{list(STATUS_RULES)}."
            )
        for name, value in (
            ("region_join", self.region_join),
            ("channel_join", self.channel_join),
        ):
            if value not in {"left", "inner", "none"}:
                raise ValueError(
                    f"Unknown {name} {value!r}. Expected left, inner or none."
                )

    @property
    def window_start(self) -> str:
        """The first instant of the reporting window."""
        return WINDOWS[self.window][0]

    @property
    def window_end(self) -> str:
        """The bound the window ends on, exclusive or inclusive as stated."""
        return WINDOWS[self.window][1]

    @property
    def window_op(self) -> str:
        """``half_open`` or ``inclusive``."""
        return WINDOWS[self.window][2]


CERTIFIED = Definition()


def _window_clause(definition: Definition) -> str:
    """The predicate that bounds the reporting period."""
    if definition.window_op == "inclusive":
        return (
            f"f.ordered_at BETWEEN '{definition.window_start}' "
            f"AND '{definition.window_end}'"
        )
    return (
        f"f.ordered_at >= '{definition.window_start}' "
        f"AND f.ordered_at < '{definition.window_end}'"
    )


def _status_clause(definition: Definition) -> str:
    """The predicate that decides which rows bear revenue.

    Both rules that book an order whose status is unknown write the null branch
    explicitly, so that the only difference between them is which statuses are
    named. Painting the null branch into one rule and not the other would make a
    single clause change have two effects, and the audit would be explaining one
    of them.
    """
    excluded = ", ".join(f"'{name}'" for name in STATUSES_NOT_REVENUE)
    if definition.status_rule == "agreed":
        return f"(f.status IS NULL OR f.status NOT IN ({excluded}))"
    if definition.status_rule == "exclude_unknown":
        return f"f.status NOT IN ({excluded})"
    return "(f.status IS NULL OR f.status <> 'CANCELLED')"


def _joins(definition: Definition) -> str:
    """The dimension joins, written out in a fixed order."""
    clauses: list[str] = []
    if definition.region_join != "none":
        clauses.append(
            f"{definition.region_join.upper()} JOIN dim_region r "
            "ON r.region_key = f.region_key"
        )
    if definition.channel_join != "none":
        clauses.append(
            f"{definition.channel_join.upper()} JOIN dim_channel c "
            "ON c.channel_key = f.channel_key"
        )
    return "\n".join(clauses)


def _source(definition: Definition, *, qualify: bool | None = None) -> str:
    """The fact table, schema qualified unless the definition says otherwise."""
    use_qualify = definition.qualify if qualify is None else qualify
    return "main.fact_order_lines" if use_qualify else "fact_order_lines"


def _deduplicate(definition: Definition, *, qualify: bool | None = None) -> tuple[str, str]:
    """The common table expression, and the predicate that keeps one row per line.

    When the definition does not deduplicate, the expression is still a common
    table expression, so that the two definitions differ in one clause rather than
    in their whole shape. The predicate becomes a tautology, which is the honest
    rendering of a definition that keeps every loaded row.
    """
    source = _source(definition, qualify=qualify)
    if definition.dedupe:
        expression = (
            "WITH deduplicated AS (\n"
            "    SELECT\n"
            "        *,\n"
            "        ROW_NUMBER() OVER (\n"
            "            PARTITION BY order_id, order_line_no\n"
            "            ORDER BY loaded_at DESC, line_id DESC\n"
            "        ) AS load_rank\n"
            f"    FROM {source}\n"
            ")\n"
        )
        return expression, "f.load_rank = 1"
    return f"WITH deduplicated AS (SELECT * FROM {source})\n", "1 = 1"


def build(definition: Definition, *, qualify: bool | None = None) -> str:
    """The SQL that reports one definition's measure.

    The query returns a single value. Everything that decides which rows are
    aggregated, and what is computed from them, is a clause of the definition, so
    a reader comparing two scenarios is comparing two fields of a dataclass rather
    than two hand written queries.
    """
    expression, rank_filter = _deduplicate(definition, qualify=qualify)
    joins = _joins(definition)
    where = (
        f"WHERE {rank_filter}\n"
        f"  AND {_window_clause(definition)}\n"
        f"  AND {_status_clause(definition)}"
    )
    if joins:
        return (
            expression
            + f"SELECT {MEASURE_EXPRESSIONS[definition.measure]} AS value\n"
            + "FROM deduplicated f\n"
            + joins
            + "\n"
            + where
            + "\n"
        )
    return (
        expression
        + f"SELECT {MEASURE_EXPRESSIONS[definition.measure]} AS value\n"
        + "FROM deduplicated f\n"
        + where
        + "\n"
    )


def build_rows(definition: Definition, *, qualify: bool | None = None) -> str:
    """The SQL that lists the fact rows a definition aggregates.

    This is the row set behind the value, generated from the same clauses. The
    audit uses it to state which rows a scenario wrongly included or excluded,
    which is the difference between saying a figure moved and showing why.
    """
    expression, rank_filter = _deduplicate(definition, qualify=qualify)
    joins = _joins(definition)
    where = (
        f"WHERE {rank_filter}\n"
        f"  AND {_window_clause(definition)}\n"
        f"  AND {_status_clause(definition)}"
    )
    body = "SELECT f.line_id\nFROM deduplicated f\n"
    if joins:
        body += joins + "\n"
    return expression + body + where + "\n"


def clarifies(definition: Definition, scenario: Definition) -> bool:
    """True when two definitions differ in exactly one clause."""
    changed = [
        name
        for name in Definition.__dataclass_fields__
        if getattr(definition, name) != getattr(scenario, name)
    ]
    return len(changed) == 1


# The anomaly families. They are the shapes a KPI defect takes in this warehouse:
# a window that covers the wrong period, a filter that removes the wrong rows, a
# join that silently drops the rows it cannot match, a grain that counts the wrong
# thing, and session state that changes what a name resolves to.
FAMILIES = ("control", "window", "filter", "join", "grain", "session")


@dataclass(frozen=True)
class Scenario:
    """One reported figure, the definition behind it, and the paperwork.

    Two definitions are stored rather than one. ``agreed`` is the definition that
    answers this scenario's question correctly, and ``definition`` is the one that
    was run. Storing both means a scenario that asks a different question, such as
    an order count, states its own correct answer instead of inheriting the
    revenue baseline, and it lets a test assert that the two differ in exactly one
    clause.

    ``claim`` is what the dashboard told its readers. ``cause`` is the mechanism,
    established from the evidence rather than asserted. ``correction`` is what
    changes. None of the three contains a number, because every number in a
    finding is measured at run time, and stating one here would be a second place
    for it to be wrong.
    """

    scenario_id: str
    title: str
    family: str
    question: str
    claim: str
    agreed: Definition
    definition: Definition
    cause: str
    correction: str
    setup: tuple[str, ...] = field(default_factory=tuple)
    notes: tuple[str, ...] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        if self.family not in FAMILIES:
            raise ValueError(
                f"Unknown family {self.family!r}. Expected one of {list(FAMILIES)}."
            )
        if self.family == "control":
            if self.definition != self.agreed:
                raise ValueError(
                    f"Scenario {self.scenario_id!r} is a control, so the definition it "
                    "ran must be the definition it should have run."
                )
        elif not clarifies(self.agreed, self.definition):
            changed = [
                name
                for name in Definition.__dataclass_fields__
                if getattr(self.agreed, name) != getattr(self.definition, name)
            ]
            raise ValueError(
                f"Scenario {self.scenario_id!r} must change exactly one clause of its "
                f"agreed definition, but changes {len(changed)}: {changed}."
            )
        if self.family == "session" and not self.setup:
            raise ValueError(
                f"Scenario {self.scenario_id!r} is a session scenario, so it must "
                "state the statements that put the session into that state."
            )
        if self.family != "session" and self.setup:
            raise ValueError(
                f"Scenario {self.scenario_id!r} is not a session scenario, so it "
                "must not run setup statements."
            )

    @property
    def changed_clause(self) -> str:
        """The name of the one clause this scenario departs from."""
        for name in Definition.__dataclass_fields__:
            if getattr(self.agreed, name) != getattr(self.definition, name):
                return name
        return ""

    @property
    def unit(self) -> str:
        """What the number is measured in, so a reader knows how to read it."""
        return MEASURE_UNITS[self.definition.measure]


SHADOW_VIEW = "fact_order_lines"
SHADOW_REGION_KEY = 1


def _scenarios() -> tuple[Scenario, ...]:
    """Every scenario, in the order they are reported."""
    return (
        Scenario(
            scenario_id="control_certified",
            title="Headline net revenue, agreed definition",
            family="control",
            question="What net revenue did the half year book?",
            claim="The dashboard reports the agreed definition unchanged.",
            agreed=CERTIFIED,
            definition=CERTIFIED,
            cause="None. The reported figure is the agreed definition, so nothing is wrong.",
            correction="None required.",
            notes=(
                "This scenario is a control. It is the one case where the audit must "
                "stay silent, which is what distinguishes checks that work from checks "
                "that fire on everything.",
            ),
        ),
        Scenario(
            scenario_id="grain_replayed_batch_counted",
            title="Cutover batch counted twice",
            family="grain",
            question="What net revenue did the half year book?",
            claim="Revenue grew on the prior half, driven by the migration backlog.",
            agreed=CERTIFIED,
            definition=replace(CERTIFIED, dedupe=False),
            cause=(
                "The cutover batch was delivered at least once. The first attempt "
                "committed its rows and then timed out, and the retry appended the "
                "same lines again, which is what an append only loader does. The load "
                "log holds one row for the batch because the retry succeeded, so a "
                "reconciliation that counts loads sees nothing wrong. Every line in "
                "the batch is therefore in the fact table twice and counted twice."
            ),
            correction=(
                "Deduplicate on the order line business key, keeping the most recently "
                "loaded row. The certified monthly and channel views already do this, "
                "which is why they disagree with the dashboard."
            ),
            notes=(
                "The batch is large because it carried the migration backlog rather "
                "than one day of trade. A retry of an ordinary day would move the "
                "headline figure by a few basis points and would survive review.",
            ),
        ),
        Scenario(
            scenario_id="window_first_month_dropped",
            title="January missing from the reporting window",
            family="window",
            question="What net revenue did the half year book?",
            claim="Half year net revenue, reported against a half year target.",
            agreed=CERTIFIED,
            definition=replace(CERTIFIED, window="FEB_TO_JUN"),
            cause=(
                "The reporting window starts on the first of February. The dashboard "
                "is labelled as a half year, and it is a five month window: January is "
                "absent, not small."
            ),
            correction=(
                "State the window from the first of January, or relabel the page as a "
                "five month view. The agreed definition is the half year, so the window "
                "is what changes."
            ),
        ),
        Scenario(
            scenario_id="window_final_day_lost",
            title="Final day lost to a closed upper bound",
            family="window",
            question="What net revenue did the half year book?",
            claim="Half year net revenue, reported to the day.",
            agreed=CERTIFIED,
            definition=replace(CERTIFIED, window="H1_CLOSED"),
            cause=(
                "The upper bound is closed, and the timestamp column carries a time of "
                "day. Every order on the final day after midnight compares greater than "
                "the bound and is dropped, so the final day contributes only the orders "
                "placed at exactly midnight, which is none of them."
            ),
            correction=(
                "Use a half open window, from the first instant of the period up to but "
                "not including the first instant of the next. A closed bound is only "
                "safe on a date column, and this column is a timestamp."
            ),
            notes=(
                "This defect is seeded small. It is the case a reviewer has to make a "
                "judgement about rather than act on, which is why the severity scale has "
                "a band below the one that demands a fix.",
            ),
        ),
        Scenario(
            scenario_id="filter_unknown_status_dropped",
            title="Orders with an unknown status dropped",
            family="filter",
            question="What net revenue did the half year book?",
            claim="Half year net revenue, excluding cancelled and returned orders.",
            agreed=CERTIFIED,
            definition=replace(CERTIFIED, status_rule="exclude_unknown"),
            cause=(
                "The status feed lags the order feed, so orders placed near the end of "
                "the period have no status yet. The exclusion is written as a negated "
                "set membership, and a null status fails every comparison, so those "
                "orders are dropped rather than kept. The intent and the predicate "
                "differ by exactly the rows whose status is unknown."
            ),
            correction=(
                "Write the rule with an explicit branch for an unknown status, so that "
                "an order is excluded when it is known to be cancelled rather than when "
                "it is not known to be live."
            ),
        ),
        Scenario(
            scenario_id="filter_returns_counted",
            title="Returned orders counted as revenue",
            family="filter",
            question="What net revenue did the half year book?",
            claim="Half year net revenue, net of cancellations.",
            agreed=CERTIFIED,
            definition=replace(CERTIFIED, status_rule="only_cancelled"),
            cause=(
                "The exclusion names cancellations only, so returned orders remain in "
                "the revenue figure. The two rules differ by one name in a list, and a "
                "return is revenue that has been given back."
            ),
            correction=(
                "Exclude returns as well as cancellations. If returns are wanted as a "
                "separate measure, report them as a deduction from gross rather than "
                "leaving them inside net revenue."
            ),
        ),
        Scenario(
            scenario_id="join_unmapped_channel_dropped",
            title="Unmapped channel rows dropped by an inner join",
            family="join",
            question="What net revenue did the half year book?",
            claim="Half year net revenue with channel attribution.",
            agreed=CERTIFIED,
            definition=replace(CERTIFIED, channel_join="inner"),
            cause=(
                "The channel dimension is loaded by a separate process from the fact, "
                "and a channel launched mid period had orders before its dimension row "
                "arrived. An inner join keeps only the fact rows it can match, so those "
                "orders are dropped from the total rather than reported against an "
                "unmapped channel."
            ),
            correction=(
                "Keep the join outer and attribute the unmatched rows to an unmapped "
                "member, so the revenue is reported and the gap in the dimension is "
                "visible rather than subtracted from the total."
            ),
        ),
        Scenario(
            scenario_id="join_unassigned_region_dropped",
            title="Orders with no region dropped by an inner join",
            family="join",
            question="What net revenue did the half year book?",
            claim="Half year net revenue with regional attribution.",
            agreed=CERTIFIED,
            definition=replace(CERTIFIED, region_join="inner"),
            cause=(
                "Some channels capture the region after the order is raised, so those "
                "fact rows carry no region. An inner join to the region dimension drops "
                "them, and the total falls by the value of every order whose region is "
                "unknown."
            ),
            correction=(
                "Keep the join outer so unassigned orders stay in the total, and report "
                "them as an unassigned region so the capture gap is visible."
            ),
        ),
        Scenario(
            scenario_id="grain_rows_counted_as_orders",
            title="Order lines counted as orders",
            family="grain",
            question="How many orders did the half year receive?",
            claim="Orders received, up on the prior half.",
            agreed=replace(CERTIFIED, measure="orders"),
            definition=replace(CERTIFIED, measure="order_lines"),
            cause=(
                "The measure counts rows, and the fact table is at order line grain, so "
                "an order with three lines counts three times. The figure is a line "
                "count that has been labelled as an order count."
            ),
            correction=(
                "Count distinct order identifiers, which is the measure the certified "
                "order count uses."
            ),
        ),
        Scenario(
            scenario_id="session_shadowed_table",
            title="A leftover session view shadows the fact table",
            family="session",
            question="What net revenue did the half year book?",
            claim="Half year net revenue, reported from the same query that produced the agreed figure.",
            agreed=CERTIFIED,
            definition=replace(CERTIFIED, qualify=False),
            setup=(
                "DROP VIEW IF EXISTS temp.fact_order_lines",
                "CREATE TEMP VIEW fact_order_lines AS "
                "SELECT * FROM main.fact_order_lines "
                f"WHERE region_key = {SHADOW_REGION_KEY}",
            ),
            cause=(
                "A temporary view named after the fact table was left in the session by "
                "an earlier debugging step, filtering to a single region. A temporary "
                "object takes precedence over a table of the same name, so the query "
                "reads the leftover view and reports one region. The query text is the "
                "agreed definition; nothing in it reveals the substitution, and the "
                "object does not appear in the schema a reviewer inspects."
            ),
            correction=(
                "Name the schema in the definition, and end a session rather than "
                "leaving objects in it. The certified views already name the schema, so "
                "they are immune; the ad hoc query is not."
            ),
            notes=(
                "This scenario is the reason the audit inspects session state rather "
                "than only query text. The defect is invisible in the query and visible "
                "in the schema the query resolved against.",
            ),
        ),
    )


ANOMALIES: tuple[Scenario, ...] = _scenarios()
ANOMALY_IDS: tuple[str, ...] = tuple(scenario.scenario_id for scenario in ANOMALIES)


def load_scenario(scenario_id: str) -> Scenario:
    """Look up one scenario by id."""
    for scenario in ANOMALIES:
        if scenario.scenario_id == scenario_id:
            return scenario
    raise KeyError(
        f"Unknown scenario {scenario_id!r}. Expected one of {list(ANOMALY_IDS)}."
    )
